#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHome Add-on for Climate control - Cool                                                 #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
##### ATTENTION: This will add climate elements to the core system and requires the core part.  #####
#####################################################################################################
---
substitutions:
  ### Local thermostat defaults ###
  temp_min: "15"

  ##### DO NOT CHANGE THIS #####
  addon_climate_cool: "true"
  ##############################

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_ADDON_CLIMATE_COOL

climate:
  - id: !extend thermostat_embedded
    min_cooling_off_time: ${min_off_time}s
    min_cooling_run_time: ${min_run_time}s
    cool_deadband: ${cool_deadband} ${temp_units}
    cool_overrun: ${cool_overrun} ${temp_units}
    cool_action:
      - switch.turn_on: relay
      - switch.turn_on: relay_2
      - switch.turn_on: relay_3
      - switch.turn_on: relay_4
      - switch.turn_on: relay_5
      - switch.turn_on: relay_6
      - switch.turn_on: relay_${cooler_relay}
      - climate.control: 
          id: thermostat_1
          mode:  "cool"
          target_temperature: 25
      - climate.control: 
          id: thermostat_2
          mode:  "cool"
          target_temperature: 25
      - climate.control: 
          id: thermostat_3
          mode:  "cool"
          target_temperature: 25
      - climate.control: 
          id: thermostat_4
          mode:  "cool"
          target_temperature: 25
      - climate.control: 
          id: thermostat_5
          mode:  "cool"
          target_temperature: 25
      - climate.control: 
          id: thermostat_6
          mode:  "cool"
          target_temperature: 25
    preset:
      - name: Fuori Casa
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"
      - name: Notturno
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"
      - name: A Casa
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"
        
  - id: !extend thermostat_1
    min_cooling_off_time: ${min_off_time}s
    min_cooling_run_time: ${min_run_time}s
    cool_deadband: ${cool_deadband} ${temp_units}
    cool_overrun: ${cool_overrun} ${temp_units}
    cool_action:
      - switch.turn_on: relay_${cooler_relay}
      - switch.turn_on: relay
    preset:
      - name: Fuori Casa
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"
      - name: Notturno
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"
      - name: A Casa
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"
        
  - id: !extend thermostat_2
    min_cooling_off_time: ${min_off_time}s
    min_cooling_run_time: ${min_run_time}s
    cool_deadband: ${cool_deadband} ${temp_units}
    cool_overrun: ${cool_overrun} ${temp_units}
    cool_action:
      - switch.turn_on: relay_${cooler_relay}
      - switch.turn_off: relay_${heater_relay}
      - switch.turn_on: relay_02
    preset:
      - name: Fuori Casa
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"
      - name: Notturno
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"
      - name: A Casa
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"
        
  - id: !extend thermostat_3
    min_cooling_off_time: ${min_off_time}s
    min_cooling_run_time: ${min_run_time}s
    cool_deadband: ${cool_deadband} ${temp_units}
    cool_overrun: ${cool_overrun} ${temp_units}
    cool_action:
      - switch.turn_on: relay_${cooler_relay}
      - switch.turn_off: relay_${heater_relay}
      - switch.turn_on: relay_03
    preset:
      - name: Fuori Casa
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"
      - name: Notturno
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"
      - name: A Casa
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"
        
  - id: !extend thermostat_4
    min_cooling_off_time: ${min_off_time}s
    min_cooling_run_time: ${min_run_time}s
    cool_deadband: ${cool_deadband} ${temp_units}
    cool_overrun: ${cool_overrun} ${temp_units}
    cool_action:
      - switch.turn_on: relay_${cooler_relay}
      - switch.turn_off: relay_${heater_relay}
      - switch.turn_on: relay_04
    preset:
      - name: Fuori Casa
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"
      - name: Notturno
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"
      - name: A Casa
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"
        
  - id: !extend thermostat_5
    min_cooling_off_time: ${min_off_time}s
    min_cooling_run_time: ${min_run_time}s
    cool_deadband: ${cool_deadband} ${temp_units}
    cool_overrun: ${cool_overrun} ${temp_units}
    cool_action:
      - switch.turn_on: relay_${cooler_relay}
      - switch.turn_off: relay_${heater_relay}
      - switch.turn_on: relay_05
    preset:
      - name: Fuori Casa
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"
      - name: Notturno
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"
      - name: A Casa
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"
        
  - id: !extend thermostat_6
    min_cooling_off_time: ${min_off_time}s
    min_cooling_run_time: ${min_run_time}s
    cool_deadband: ${cool_deadband} ${temp_units}
    cool_overrun: ${cool_overrun} ${temp_units}
    cool_action:
      - switch.turn_on: relay_${cooler_relay}
      - switch.turn_off: relay_${heater_relay}
      - switch.turn_on: relay_06
    preset:
      - name: Fuori Casa
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"
      - name: Notturno
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"
      - name: A Casa
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"

packages:
  climate_base_package: !include nspanel_esphome_addon_climate_base.yaml
...
