#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHome Add-on for Climate control - Heat                                                 #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
##### ATTENTION: This will add climate elements to the core system and requires the core part.  #####
#####################################################################################################
---
substitutions:
  ### Local thermostat defaults ###
  temp_max: "25"

  ##### DO NOT CHANGE THIS #####
  addon_climate_heat: "true"
  ##############################

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_ADDON_CLIMATE_HEAT

climate:
  - id: !extend thermostat_embedded
    min_heating_off_time: ${min_off_time}s
    min_heating_run_time: ${min_run_time}s
    heat_deadband: ${heat_deadband} ${temp_units}
    heat_overrun: ${heat_overrun} ${temp_units}
    heat_action:
      - switch.turn_on: relay
      - switch.turn_on: relay_2
      - switch.turn_on: relay_3
      - switch.turn_on: relay_4
      - switch.turn_on: relay_5
      - switch.turn_on: relay_6
      - switch.turn_on: relay_7
      - switch.turn_on: relay_8
      - switch.turn_on: relay_${heater_relay}
      - climate.control: 
          id: thermostat_1
          mode: HEAT
          target_temperature: 21
      - climate.control: 
          id: thermostat_2
          mode: HEAT
          target_temperature: 21
      - climate.control: 
          id: thermostat_3
          mode: HEAT
          target_temperature: 21
      - climate.control: 
          id: thermostat_4
          mode: HEAT
          target_temperature: 21
      - climate.control: 
          id: thermostat_5
          mode: HEAT
          target_temperature: 21
      - climate.control: 
          id: thermostat_6
          mode: HEAT
          target_temperature: 21
    preset:
      - name: Fuori Casa
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"
      - name: Notturno
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"
      - name: A Casa
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"
        
  - id: !extend thermostat_1
    min_heating_off_time: ${min_off_time}s
    min_heating_run_time: ${min_run_time}s
    heat_deadband: ${heat_deadband} ${temp_units}
    heat_overrun: ${heat_overrun} ${temp_units}
    heat_action:
      - switch.turn_on: relay_${heater_relay}
      - switch.turn_on: relay
    preset:
      - name: Fuori Casa
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"
      - name: Notturno
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"
      - name: A Casa
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"
        
  - id: !extend thermostat_2
    min_heating_off_time: ${min_off_time}s
    min_heating_run_time: ${min_run_time}s
    heat_deadband: ${heat_deadband} ${temp_units}
    heat_overrun: ${heat_overrun} ${temp_units}
    heat_action:
      - switch.turn_on: relay_${heater_relay}
      - switch.turn_on: relay_02
    preset:
      - name: Fuori Casa
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"
      - name: Notturno
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"
      - name: A Casa
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"
        
  - id: !extend thermostat_3
    min_heating_off_time: ${min_off_time}s
    min_heating_run_time: ${min_run_time}s
    heat_deadband: ${heat_deadband} ${temp_units}
    heat_overrun: ${heat_overrun} ${temp_units}
    heat_action:
      - switch.turn_on: relay_${heater_relay}
      - switch.turn_on: relay_03
    preset:
      - name: Fuori Casa
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"
      - name: Notturno
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"
      - name: A Casa
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"
        
  - id: !extend thermostat_4
    min_heating_off_time: ${min_off_time}s
    min_heating_run_time: ${min_run_time}s
    heat_deadband: ${heat_deadband} ${temp_units}
    heat_overrun: ${heat_overrun} ${temp_units}
    heat_action:
      - switch.turn_on: relay_${heater_relay}
      - switch.turn_on: relay_04
    preset:
      - name: Fuori Casa
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"
      - name: Notturno
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"
      - name: A Casa
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"
        
  - id: !extend thermostat_5
    min_heating_off_time: ${min_off_time}s
    min_heating_run_time: ${min_run_time}s
    heat_deadband: ${heat_deadband} ${temp_units}
    heat_overrun: ${heat_overrun} ${temp_units}
    heat_action:
      - switch.turn_on: relay_${heater_relay}
      - switch.turn_on: relay_05
    preset:
      - name: Fuori Casa
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"
      - name: Notturno
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"
      - name: A Casa
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"
        
  - id: !extend thermostat_6
    min_heating_off_time: ${min_off_time}s
    min_heating_run_time: ${min_run_time}s
    heat_deadband: ${heat_deadband} ${temp_units}
    heat_overrun: ${heat_overrun} ${temp_units}
    heat_action:
      - switch.turn_on: relay_${heater_relay}
      - switch.turn_on: relay_06
    preset:
      - name: Fuori Casa
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"
      - name: Notturno
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"
      - name: A Casa
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat"

packages:
  climate_base_package: !include nspanel_esphome_addon_climate_base.yaml
...
